tutorial_old/config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'posts', to: 'post#index'
    get 'posts/new', to: 'post#new'
    post 'posts', to: 'post#create'
    get 'posts/:id', to: 'post#show', as: :post
    get 'posts/:id/edit', to: 'post#edit', as: :edit_post
    patch 'posts/:id', to: 'post#update'
    delete 'posts/:id/delete', to: 'post#destroy', as: :delete_post
end

tutorial_old/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tutorial_old/app/models/post.rb
class Post < ApplicationRecord
end

tutorial_old/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tutorial_old/app/controllers/post_controller.rb
class PostController < ApplicationController
    def index
        @post_data = Post.all.order("created_at DESC");
        #p @post_data
    end

    def new
        @post = Post.new();
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path
        else
            render :new
        end
    end

    def show
        @post_single_data = Post.find(params[:id]);
    end

    def edit
        @post_edit_data = Post.find(params[:id]);

        Rails.logger.debug("My object: #{@post_edit_data.inspect}");
    end

    def update
        @post_update_data = Post.find(params[:id]);
        if @post_update_data.update(post_params)
            redirect_to posts_path
        else
            render :new
        end
    end

    def destroy
        @post_delete_data = Post.find(params[:id]);
        @post_delete_data.destroy

        redirect_to posts_path
    end

    private
    def post_params
        params.required(:post).permit(:title, :body)
    end
end

tutorial_old/app/helpers/application_helper.rb
module ApplicationHelper
end

tutorial_old/app/helpers/post_helper.rb
module PostHelper
end

tutorial_old/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tutorial_old/app/views/post/edit.html.erb
<h1>Edit Post</h1>

<%= simple_form_for(@post_edit_data) do |f| %>

<%= f.input :title %> <br>

<%= f.input :body %> <br>

<%= f.submit %>

<% end %>

tutorial_old/app/views/post/form.html.erb
<%= simple_form_for(@post) do |f| %>

<%= f.input :title,  %> <br>

<%= f.input :body %> <br>

<%= f.submit %>

<% end %>

tutorial_old/app/views/post/index.html.erb
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>

<%= link_to "New Post", posts_new_path %>

<br><br>

<table style="width:100%">
    <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Created At</th>
        <th>Actions</th>
    </tr>

    <% @post_data.each do |posts| %>
        <tr>
            <td>
                <%= posts.title %>
            </td>

            <td>
                <%= posts.body %>
            </td>

            <td>
                <%= posts.created_at %>
            </td>

            <td>
                <%= link_to "show", posts %> <br>
                <%= link_to "edit", edit_post_path(posts) %> <br>
                <%= link_to "delete", delete_post_path(posts), method: :delete %>
            </td>
        </tr>
    <% end %>
</table>

tutorial_old/app/views/post/new.html.erb
<h1> New Post </h1>

<%= simple_form_for(@post) do |f| %>

<%= f.input :title %> <br>

<%= f.input :body %> <br>

<%= f.submit %>

<% end %>

tutorial_old/app/views/post/show.html.erb
<label>Title:</label> <%= @post_single_data.title %> <br>
<label>Body:</label> <%= @post_single_data.body %> <br><br><br>

<%= link_to "All Posts", posts_path %>